apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-deployment
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: docker.io/yuva0606/inventory-service  # Replace with your actual Inventory Service image
          ports:
            - containerPort: 8080  # Adjust based on your Inventory Service port
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  ports:
    - port: 8080  # Adjust based on your Inventory Service port
      targetPort: 8080
  selector:
    app: inventory-service
