apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: inventorydb
          ports:
            - containerPort: 3306
      initContainers:
        - name: create-databases
          image: mysql:5.7
          command:
            - bash
            - -c
            - |
              # Wait for MySQL to start
              until mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'; do
                echo "Waiting for mysql to start..."
                sleep 5
              done
              # Create other databases
              mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS userdb;'
              mysql -h 127.0.0.1 -u root -p$MYSQL_ROOT_PASSWORD -e 'CREATE DATABASE IF NOT EXISTS orderdb;'
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root